insert into article(title, content) values('가','1');
insert into article(title, content) values('나','2');
insert into article(title, content) values('다','3');
insert into coffee(name, price) values('아메리카노','4500');
insert into coffee(name, price) values('라뗴','5000');
insert into coffee(name, price) values('카페모카','5500');
insert into article(title, content) values('당신의 인생 영화는?','댓글고');
insert into article(title, content) values('음식','댓글');
insert into article(title, content) values('취미','댓글');
insert into comment(article_id, nickname, body) VALUES(4,'park','굿윌헌팅');
insert into comment(article_id, nickname, body) VALUES(4,'kim','아이엠샘');
insert into comment(article_id, nickname, body) VALUES(4,'choi','쇼생크탈출');
insert into comment(article_id, nickname, body) VALUES(5,'park','치킨');
insert into comment(article_id, nickname, body) VALUES(5,'kim','샤브샤브');
insert into comment(article_id, nickname, body) VALUES(5,'choi','초밥');
insert into comment(article_id, nickname, body) VALUES(6,'park','조깅');
insert into comment(article_id, nickname, body) VALUES(6,'kim','유튜브');
insert into comment(article_id, nickname, body) VALUES(6,'choi','독서');
